services:
  db:
    image: postgres:17-alpine
    container_name: ses_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dockerfiles/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - ses-db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
  app: &app
    build:
      dockerfile: ./dockerfiles/php/dockerfile
    restart: unless-stopped
    container_name: ses-app
    environment:
      COMMAND: php artisan octane:start --host=0.0.0.0 --port=8000
      PROCESS: app
      APP_NAME: "${APP_NAME}"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "${APP_URL}"

      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      WEATHER_API_KEY: "${WEATHER_API_KEY}"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - app_public:/var/www/public
      - ses_app_composer_data:/.composer
      - ses_app_npm_data:/.npm
    networks:
      - ses-db-network
      - ses-webserver-network
      - ses-redis-network
    healthcheck:
      test: curl -s http://localhost:8000/up >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 20

  schedule:
    <<: *app
    container_name: ses-schedule
    environment:
      COMMAND: supercronic -quiet /var/www/docker/php/schedule/crontab
      PROCESS: schedule
      APP_ENV: production
      APP_DEBUG: "false"
    networks:
      - ses-db-network
      - ses-redis-network
    healthcheck:
      test: supercronic -test /var/www/docker/php/schedule/crontab | grep -q 'is valid'
      interval: 5s
      timeout: 10s
      retries: 2

  webserver:
    image: nginx:1.26.0-alpine
    container_name: ses-webserver
    restart: unless-stopped
    volumes:
      - app_public:/var/www/public:ro
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/logs/nginx/:/var/log/nginx/
    ports:
      - 80:80
    networks:
      - ses-webserver-network
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: curl -s http://localhost/up >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 20

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    container_name: ses-redis
    command:
      - "redis-server"
      - "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - ses-redis-network
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 20

volumes:
  db_data:
    driver: local
    name: ses_db_data
  redis_data:
    driver: local
    name: ses_redis_data
  ses_app_composer_data:
    driver: local
    name: ses_app_composer_data
  ses_app_npm_data:
    driver: local
    name: ses_app_npm_data
  app_public:
    driver: local
    name: ses_app_public

networks:
  ses-db-network:
    driver: bridge
    name: ses-db-network
  ses-webserver-network:
    driver: bridge
    name: ses-webserver-network
  ses-redis-network:
    driver: bridge
    name: ses-redis-network
